GEMINI_API_KEY = "AIzaSyAHnBTWy3wLzGp89yQ0zXecAZObtAscXIE"
GAS_API_URL = "https://script.google.com/macros/s/AKfycbzpxWcyKA__TZNcsJmylCQIua4kbDm7tpHlTTugPVjJZJVXMxDXhHGDca1xCcXrk1sR/exec"
NOTION_API_KEY = "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"
NOTION_EC_DATABASE_ID = "3b75acff6ac588569298c4254fb66105"